<?php echo $this->doctype() ?>
<html lang="ja">
  <head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(array(
        'rel' => 'shortcut icon', 
        'href' => $this->baseUrl('/favicon.ico')
      ), 'PREPEND')
    ?>
    <?php 
    echo $this->jQuery()
        // Twitter bootstrap
        ->addJavaScriptFile($this->baseUrl('/js/bootstrap.js'))
        ->addStylesheet($this->baseUrl('/css/bootstrap.css'))
        ->addStylesheet($this->baseUrl('/css/base.css'))
    ?>
    <title>簡単な認証サンプル</title>
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="<?php echo $this->baseUrl('/')?>">簡単な認証サンプル</a>
        <?php if ($this->userinfo) : // {{{?>
        <div class="btn-group pull-right">
          <a class="btn dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-user"></i> (<?php echo $this->escape($this->userinfo->account)?>)<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo $this->url(array('action' => 'logout', 'controller' => 'auth', 'module' => 'default'))?>">ログアウト</a></li>
          </ul>
        </div>
        <?php endif; // }}} ?>
        </div>
      </div>
    </div>

    <div class="container">
        <?php echo $this->layout()->content; ?>
    </div>
  </body>

</html>
<?php // vim:set ts=2 sts=2 sw=2 expandtab fdm=marker: ?>
